//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações a este ficheiro poderão provocar um comportamento incorrecto e perder-se-ão se
//     o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebApplication4.Healthipcasoap {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="HealthIPCAsoapSoap", Namespace="https://healthipcasoap.azurewebsites.net/")]
    public partial class HealthIPCAsoap : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DaConsultasOperationCompleted;
        
        private System.Threading.SendOrPostCallback DaConsultasTodasOperationCompleted;
        
        private System.Threading.SendOrPostCallback DaUtentesTodosOperationCompleted;
        
        private System.Threading.SendOrPostCallback DaUtenteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public HealthIPCAsoap() {
            this.Url = global::WebApplication4.Properties.Settings.Default.WebApplication4_healthipcasoap_HealthIPCAsoap;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DaConsultasCompletedEventHandler DaConsultasCompleted;
        
        /// <remarks/>
        public event DaConsultasTodasCompletedEventHandler DaConsultasTodasCompleted;
        
        /// <remarks/>
        public event DaUtentesTodosCompletedEventHandler DaUtentesTodosCompleted;
        
        /// <remarks/>
        public event DaUtenteCompletedEventHandler DaUtenteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://healthipcasoap.azurewebsites.net/DaConsultas", RequestNamespace="https://healthipcasoap.azurewebsites.net/", ResponseNamespace="https://healthipcasoap.azurewebsites.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Consulta[] DaConsultas(string data) {
            object[] results = this.Invoke("DaConsultas", new object[] {
                        data});
            return ((Consulta[])(results[0]));
        }
        
        /// <remarks/>
        public void DaConsultasAsync(string data) {
            this.DaConsultasAsync(data, null);
        }
        
        /// <remarks/>
        public void DaConsultasAsync(string data, object userState) {
            if ((this.DaConsultasOperationCompleted == null)) {
                this.DaConsultasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDaConsultasOperationCompleted);
            }
            this.InvokeAsync("DaConsultas", new object[] {
                        data}, this.DaConsultasOperationCompleted, userState);
        }
        
        private void OnDaConsultasOperationCompleted(object arg) {
            if ((this.DaConsultasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DaConsultasCompleted(this, new DaConsultasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://healthipcasoap.azurewebsites.net/DaConsultasTodas", RequestNamespace="https://healthipcasoap.azurewebsites.net/", ResponseNamespace="https://healthipcasoap.azurewebsites.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Consulta[] DaConsultasTodas() {
            object[] results = this.Invoke("DaConsultasTodas", new object[0]);
            return ((Consulta[])(results[0]));
        }
        
        /// <remarks/>
        public void DaConsultasTodasAsync() {
            this.DaConsultasTodasAsync(null);
        }
        
        /// <remarks/>
        public void DaConsultasTodasAsync(object userState) {
            if ((this.DaConsultasTodasOperationCompleted == null)) {
                this.DaConsultasTodasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDaConsultasTodasOperationCompleted);
            }
            this.InvokeAsync("DaConsultasTodas", new object[0], this.DaConsultasTodasOperationCompleted, userState);
        }
        
        private void OnDaConsultasTodasOperationCompleted(object arg) {
            if ((this.DaConsultasTodasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DaConsultasTodasCompleted(this, new DaConsultasTodasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://healthipcasoap.azurewebsites.net/DaUtentesTodos", RequestNamespace="https://healthipcasoap.azurewebsites.net/", ResponseNamespace="https://healthipcasoap.azurewebsites.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Utente[] DaUtentesTodos() {
            object[] results = this.Invoke("DaUtentesTodos", new object[0]);
            return ((Utente[])(results[0]));
        }
        
        /// <remarks/>
        public void DaUtentesTodosAsync() {
            this.DaUtentesTodosAsync(null);
        }
        
        /// <remarks/>
        public void DaUtentesTodosAsync(object userState) {
            if ((this.DaUtentesTodosOperationCompleted == null)) {
                this.DaUtentesTodosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDaUtentesTodosOperationCompleted);
            }
            this.InvokeAsync("DaUtentesTodos", new object[0], this.DaUtentesTodosOperationCompleted, userState);
        }
        
        private void OnDaUtentesTodosOperationCompleted(object arg) {
            if ((this.DaUtentesTodosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DaUtentesTodosCompleted(this, new DaUtentesTodosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://healthipcasoap.azurewebsites.net/DaUtente", RequestNamespace="https://healthipcasoap.azurewebsites.net/", ResponseNamespace="https://healthipcasoap.azurewebsites.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Utente DaUtente(int numprocesso) {
            object[] results = this.Invoke("DaUtente", new object[] {
                        numprocesso});
            return ((Utente)(results[0]));
        }
        
        /// <remarks/>
        public void DaUtenteAsync(int numprocesso) {
            this.DaUtenteAsync(numprocesso, null);
        }
        
        /// <remarks/>
        public void DaUtenteAsync(int numprocesso, object userState) {
            if ((this.DaUtenteOperationCompleted == null)) {
                this.DaUtenteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDaUtenteOperationCompleted);
            }
            this.InvokeAsync("DaUtente", new object[] {
                        numprocesso}, this.DaUtenteOperationCompleted, userState);
        }
        
        private void OnDaUtenteOperationCompleted(object arg) {
            if ((this.DaUtenteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DaUtenteCompleted(this, new DaUtenteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://healthipcasoap.azurewebsites.net/")]
    public partial class Consulta {
        
        private string idField;
        
        private int episodioField;
        
        private string moduloField;
        
        private int processoField;
        
        private string dataField;
        
        private string horaField;
        
        private string especialidadeField;
        
        /// <observações/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <observações/>
        public int Episodio {
            get {
                return this.episodioField;
            }
            set {
                this.episodioField = value;
            }
        }
        
        /// <observações/>
        public string Modulo {
            get {
                return this.moduloField;
            }
            set {
                this.moduloField = value;
            }
        }
        
        /// <observações/>
        public int Processo {
            get {
                return this.processoField;
            }
            set {
                this.processoField = value;
            }
        }
        
        /// <observações/>
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <observações/>
        public string Hora {
            get {
                return this.horaField;
            }
            set {
                this.horaField = value;
            }
        }
        
        /// <observações/>
        public string Especialidade {
            get {
                return this.especialidadeField;
            }
            set {
                this.especialidadeField = value;
            }
        }
    }
    
    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://healthipcasoap.azurewebsites.net/")]
    public partial class Utente {
        
        private int processoField;
        
        private string nomeField;
        
        private string dataNascimentoField;
        
        private string sexoField;
        
        /// <observações/>
        public int Processo {
            get {
                return this.processoField;
            }
            set {
                this.processoField = value;
            }
        }
        
        /// <observações/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <observações/>
        public string DataNascimento {
            get {
                return this.dataNascimentoField;
            }
            set {
                this.dataNascimentoField = value;
            }
        }
        
        /// <observações/>
        public string Sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DaConsultasCompletedEventHandler(object sender, DaConsultasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DaConsultasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DaConsultasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Consulta[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Consulta[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DaConsultasTodasCompletedEventHandler(object sender, DaConsultasTodasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DaConsultasTodasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DaConsultasTodasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Consulta[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Consulta[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DaUtentesTodosCompletedEventHandler(object sender, DaUtentesTodosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DaUtentesTodosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DaUtentesTodosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Utente[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Utente[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DaUtenteCompletedEventHandler(object sender, DaUtenteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DaUtenteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DaUtenteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Utente Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Utente)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591